### ISSUE TITLE
Can't use '&' for color codes in name variable.

### ISSUE THREAD

**Issue by mibby** [goncalomb/NBTEditor#17]
NBTEditor v3 compiled as of commit https://github.com/goncalomb/NBTEditor/commit/c3a72b15256f7d8bb813f807f3109dc487b7e882

```/nbti var Name &btest```

Doesn't change the name of the item to a blue "test".

**Comment by goncalomb** [comment]
Thanks for reporting, should be fixed now.

**Comment by mibby** [comment]
@goncalomb I'm getting reports that this still isn't working. Not able to use a color code in the name to colorize items. Such as with ```/nbti var name &bhello```. I'm guessing using color codes in the lore would also be broken if it doesn't interpret ```&<code>```.

Edit: Testing myself to confirm, it seems to work fine. So I'm not sure why he wasn't able to use color codes. However I did notice there is a bit of delay before the item updates with the specified name / color code. Maybe because of the delay, if you open your inventory after typing the command, it doesn't refresh the item?

**Comment by goncalomb** [comment]
I'm not sure how the delay affects the update of the NBT tags. It may be caused by the server not sending the updated NBT tags to the client right away (I don't know how the internals work). As far as the NBTEditor is concerned, all the NBT changes happen on the same tick (there is no added delay).
If it becomes a problem in the future, I'll investigate it.
